---
- name: HOST SETUP
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: 10.34.56.233
    api: 89a9356f-c203-d263-8a89-c229486a13ba
  tasks:
    - name: CREATE HOST
      purestorage.flasharray.purefa_host:
        name: "{{ ansible_hostname }}"
        iqn: "{{ ansible_iscsi_iqn }}"
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
