---
- name: PROTECTION GROUP SETUP
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: 10.34.56.233
    api: 89a9356f-c203-d263-8a89-c229486a13ba
  tasks:
    - name: CREATE PROTECTION GROUP
      purestorage.flasharray.purefa_pg:
        name: workshop_pg
        volume:
          - volume_b
          - volume_c
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
