---
- name: INFRASTRUCTURE SETTINGS
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: 10.34.56.233
    api: 89a9356f-c203-d263-8a89-c229486a13ba
  tasks:
    - name: CONFIGURE NTP
      purestorage.flasharray.purefa_ntp:
        ntp_servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
        fa_url: "{{ url }}"
        api_token: "{{ api }}"

    - name: CONFIGURE DNS
      purestorage.flasharray.purefa_dns:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        fa_url: "{{ url }}"
        api_token: "{{ api }}"

    - name: CONFIGURE SYSLOG
      purestorage.flasharray.purefa_syslog:
        name: acme_syslog
        address: syslog.acme.com
        port: 514
        protocol: tcp
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
