---
- name: PROTECTION GROUP SCHEDULING
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: 10.34.56.233
    api: 89a9356f-c203-d263-8a89-c229486a13ba
  tasks:
    - name: LOCAL SNAP SCHEDULE
      purestorage.flasharray.purefa_pgsched:
        name: workshop-pg
        schedule: snapshot
        enabled: true
        snap_frequency: 86400
        snap_at: 15:30:00
        days: 2
        per_day: 5
        all_for: 4
        fa_url: "{{ url }}"
        api_token: "{{ api }}"

    - name: REPLICATION SCHEDULE
      purestorage.flasharray.purefa_pgsched:
        name: workshop-pg
        schedule: replication
        replicate_frequency: 3600
        target_per_day: 10
        target_all_for: 7
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
