---
- name: FA-FILES DNS
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: 10.34.56.233
    api: 89a9356f-c203-d263-8a89-c229486a13ba
  tasks:
    - name: CONFIGURE FILES DNS
      purestorage.flasharray.purefa_dns:
        domain: purestorage.com
        nameservers:
          - dns1.acme.com
          - dns2.acme.com
        name: file_dns
        service: file
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
