---
- name: ASYNC SETUP
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    url: 10.34.56.233
    api: 89a9356f-c203-d263-8a89-c229486a13ba
    target_url: 10.34.56.243
    target_api: 33ed2a76-3e45-12dd-cf55-d4489ac44533
  tasks:
    - name: TARGET INFO
      purestorage.flasharray.purefa_info:
        fa_url: "{{ target_url }}"
        api_token: "{{ target_api }}"
      register: target_array

    - name: UPDATE PG
      purestorage.flasharray.purefa_pg:
        name: workshop-pg
        target: "{{ target_array['purefa_info']['default']['array_name'] }}"
        fa_url: "{{ url }}"
        api_token: "{{ api }}"
